services:
  db:
    image: mysql:5.7
    container_name: sqli-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab_db
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sqli-pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db